// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXY0-tx_xeAOwIXnMDiUpxgOp9a2Ox2w0',
    appId: '1:1051520652945:web:ce844ca140696a951f9130',
    messagingSenderId: '1051520652945',
    projectId: 'flutter-firebase-emulator-demo',
    authDomain: 'flutter-firebase-emulator-demo.firebaseapp.com',
    storageBucket: 'flutter-firebase-emulator-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wdD-XyG2J9zZPmNugLM6FZHDSeI1fWw',
    appId: '1:1051520652945:android:481374dca42a60121f9130',
    messagingSenderId: '1051520652945',
    projectId: 'flutter-firebase-emulator-demo',
    storageBucket: 'flutter-firebase-emulator-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIssKS7ByzZUiyR_VKzZB0t44rBjNvq8',
    appId: '1:1051520652945:ios:69744a39fafd5c891f9130',
    messagingSenderId: '1051520652945',
    projectId: 'flutter-firebase-emulator-demo',
    storageBucket: 'flutter-firebase-emulator-demo.appspot.com',
    iosClientId: '1051520652945-av1896rfm6mabtgtrktli211ss7rm771.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseEmulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDIssKS7ByzZUiyR_VKzZB0t44rBjNvq8',
    appId: '1:1051520652945:ios:69744a39fafd5c891f9130',
    messagingSenderId: '1051520652945',
    projectId: 'flutter-firebase-emulator-demo',
    storageBucket: 'flutter-firebase-emulator-demo.appspot.com',
    iosClientId: '1051520652945-av1896rfm6mabtgtrktli211ss7rm771.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseEmulator',
  );
}
